# Initial Setting
I started off trying to translate the R code to Python, however there were problems trying to formate the data.
I used R Studio to run the R code again. This code worked, however due to file size the code only ran until line 35, from here the data was too large to process.
Therefore I loaded the CSV that R had outputted and continued using Python.

Steps:
 1. sample 10/100K rows
 2. split : meta & drug db
 3. define transform from R code.
 4. apply transforms.
 5. train model.

# Load Data

In [1]:
import pandas as pd

C:\ProgramData\Miniconda3\envs\machine-learning\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

In [2]:
pres = pd.read_csv(r"P:/data_science/prescriber-info.csv", header=0, sep=",", nrows = 100000)

In [3]:
meta = pd.read_csv(r"D:/NPI/PartD_Prescriber_PUF_NPI_17.txt", header=0, sep="\t", nrows =12898)

In [4]:
pres

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_city,nppes_provider_state,specialty_description,description_flag,drug_name,generic_name,bene_count,...,total_30_day_fill_count,total_day_supply,total_drug_cost,bene_count_ge65,bene_count_ge65_suppress_flag,total_claim_count_ge65,ge65_suppress_flag,total_30_day_fill_count_ge65,total_day_supply_ge65,total_drug_cost_ge65
0,1003000126,ENKESHAFI,ARDALAN,CUMBERLAND,MD,Internal Medicine,S,AMLODIPINE.BESYLATE,AMLODIPINE BESYLATE,NaN,...,13.0,390,59.21,NaN,*,NaN,*,NaN,NaN,NaN
1,1003000126,ENKESHAFI,ARDALAN,CUMBERLAND,MD,Internal Medicine,S,ATORVASTATIN.CALCIUM,ATORVASTATIN CALCIUM,11.0,...,27.0,765,259.48,NaN,#,NaN,#,NaN,NaN,NaN
2,1003000126,ENKESHAFI,ARDALAN,CUMBERLAND,MD,Internal Medicine,S,CEPHALEXIN,CEPHALEXIN,17.0,...,17.0,123,98.99,NaN,#,NaN,#,NaN,NaN,NaN
3,1003000126,ENKESHAFI,ARDALAN,CUMBERLAND,MD,Internal Medicine,S,CIPROFLOXACIN.HCL,CIPROFLOXACIN HCL,11.0,...,12.0,95,120.43,NaN,*,NaN,*,NaN,NaN,NaN
4,1003000126,ENKESHAFI,ARDALAN,CUMBERLAND,MD,Internal Medicine,S,DOXYCYCLINE.HYCLATE,DOXYCYCLINE HYCLATE,17.0,...,17.0,105,300.76,NaN,#,NaN,#,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1003823527,AVILES MUNOZ,NELSON,HATILLO,PR,Family Practice,S,VALSARTAN,VALSARTAN,NaN,...,36.0,1080,458.04,NaN,*,32.0,NaN,36.0,1080.0,458.04
99996,1003823527,AVILES MUNOZ,NELSON,HATILLO,PR,Family Practice,S,VENTOLIN.HFA,ALBUTEROL SULFATE,16.0,...,85.6,2169,4663.49,NaN,#,66.0,NaN,66.9,1669.0,3756.77
99997,1003823527,AVILES MUNOZ,NELSON,HATILLO,PR,Family Practice,S,VERAPAMIL.ER,VERAPAMIL HCL,NaN,...,29.0,870,422.30,NaN,*,28.0,NaN,29.0,870.0,422.30
99998,1003823527,AVILES MUNOZ,NELSON,HATILLO,PR,Family Practice,S,WARFARIN.SODIUM,WARFARIN SODIUM,NaN,...,30.3,893,230.73,NaN,*,28.0,NaN,30.3,893.0,230.73
99999,1003823527,AVILES MUNOZ,NELSON,HATILLO,PR,Family Practice,S,XARELTO,RIVAROXABAN,NaN,...,24.0,720,9755.33,NaN,#,NaN,#,NaN,NaN,NaN

In [5]:
meta

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,...,beneficiary_male_count,beneficiary_race_white_count,beneficiary_race_black_count,beneficiary_race_asian_pi_count,beneficiary_race_hispanic_count,beneficiary_race_nat_ind_count,beneficiary_race_other_count,beneficiary_nondual_count,beneficiary_dual_count,beneficiary_average_risk_score
0,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,92.0,220.0,14.0,0.0,0.0,0.0,0.0,143.0,91.0,2.1685
1,1003000142,KHALIL,RASHID,NaN,M.D.,M,I,4126 N HOLLAND SYLVANIA RD,SUITE 220,TOLEDO,...,92.0,195.0,58.0,NaN,NaN,0.0,NaN,143.0,133.0,1.8029
2,1003000167,ESCOBAR,JULIO,E,DDS,M,I,5 PINE CONE RD,NaN,DAYTON,...,17.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,1.0598
3,1003000175,REYES-VASQUEZ,BELINDA,NaN,D.D.S.,F,I,322 N AZUSA AVE STE 202,NaN,LA PUENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1003000282,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,...,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,4.5148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12893,1013056357,FAIRBANKS,GRANT,A,MD,M,I,1151 EAST 3900 SOUTH,SUITE #B110,SALT LAKE CITY,...,NaN,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,0.6072
12894,1013056365,ZEMANKIEWICZ,NORBERT,NaN,D.O.,M,I,1838 GREENE TREE RD,SUITE 285,PIKESVILLE,...,53.0,NaN,53.0,0.0,NaN,0.0,NaN,79.0,29.0,2.2748
12895,1013056464,SCHMIDT,JILL,M,PA-C,F,I,1005 W GREEN ST,NaN,HASTINGS,...,35.0,86.0,NaN,0.0,NaN,0.0,NaN,75.0,22.0,1.2841
12896,1013056555,LARKIN,MARY,R,MD,F,I,1929 23RD AVE,NaN,MERIDIAN,...,158.0,NaN,197.0,0.0,NaN,0.0,NaN,65.0,301.0,1.1651
12897,1013056761,KIM,EUGENE,NaN,M.D.,M,I,2929 DESERT STORM DR,"USASOC (AOMD), ATTN: SURGEON SECTION",FORT BRAGG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Pivot and Format R data w/ meta

In [6]:
pivot_data = pres.pivot(index='npi',columns='drug_name', values='total_claim_count')

In [7]:
pivot_data

drug_name,ACETAMINOPHEN.CODEINE,ACYCLOVIR,ADVAIR.DISKUS,ALENDRONATE.SODIUM,ALLOPURINOL,ALPHAGAN.P,ALPRAZOLAM,AMIODARONE.HCL,AMITIZA,AMITRIPTYLINE.HCL,...,VENTOLIN.HFA,VERAPAMIL.ER,VESICARE,VICTOZA.3.PAK,VOLTAREN,WARFARIN.SODIUM,XARELTO,ZETIA,ZIPRASIDONE.HCL,ZOLPIDEM.TARTRATE
npi,,,,,,,,,,,,,,,,,,,,,
1003000126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23.0,NaN,NaN,NaN
1003000142,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003000167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003000282,NaN,NaN,NaN,NaN,22.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003000407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003823428,NaN,NaN,NaN,NaN,18.0,NaN,14.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003823436,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003823469,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,28.0
1003823501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003823527,NaN,NaN,52.0,106.0,31.0,NaN,NaN,NaN,NaN,36.0,...,82.0,28.0,NaN,NaN,NaN,28.0,24.0,NaN,NaN,NaN

In [8]:
format_data = meta[['npi','nppes_provider_gender', 'nppes_provider_state', 'nppes_credentials', 'specialty_description']]

In [9]:
merge_data = format_data.merge(pivot_data, left_on='npi', right_on="npi")

In [10]:
final_data = merge_data.fillna(0)

In [11]:
final_data

,npi,nppes_provider_gender,nppes_provider_state,nppes_credentials,specialty_description,ACETAMINOPHEN.CODEINE,ACYCLOVIR,ADVAIR.DISKUS,ALENDRONATE.SODIUM,ALLOPURINOL,...,VENTOLIN.HFA,VERAPAMIL.ER,VESICARE,VICTOZA.3.PAK,VOLTAREN,WARFARIN.SODIUM,XARELTO,ZETIA,ZIPRASIDONE.HCL,ZOLPIDEM.TARTRATE
0,1003000126,M,MD,M.D.,Internal Medicine,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0
1,1003000142,M,OH,M.D.,Anesthesiology,46.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1003000167,M,NV,DDS,Dentist,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1003000282,F,TN,FNP,Nurse Practitioner,0.0,0.0,0.0,0.0,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1003000407,M,PA,D.O.,Family Practice,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4773,1003823428,F,FL,NP,Nurse Practitioner,0.0,0.0,0.0,0.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4774,1003823436,M,WI,DDS,Dentist,42.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4775,1003823469,M,GA,M.D.,Psychiatry & Neurology,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,28.0
4776,1003823501,M,CA,DDS,Dentist,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4777,1003823527,M,PR,M.D.,Family Practice,0.0,0.0,52.0,106.0,31.0,...,82.0,28.0,0.0,0.0,0.0,28.0,24.0,0.0,0.0,0.0

In [12]:
final_data.to_csv(r"P:/data_science/github/Medication_Prediction/SortedData/prescriber-info-test1.csv")