In [1]:
import pandas as pd
import random

In [2]:
row_number = 100000
num_drugs = 300

In [3]:
prescriber_info = pd.read_csv(r"D:/NPI/PartD_Prescriber_PUF_NPI_Drug_17.txt", header=0, sep="\t", nrows = row_number)

In [4]:
meta = pd.read_csv(r"D:/NPI/PartD_Prescriber_PUF_NPI_17.txt", header=0, sep="\t", nrows = 100000)

In [5]:
#get the most prescribed drugs and return a sample from that list
drug_list = prescriber_info['drug_name'].value_counts(900).keys()#get a list of all drug names in order and select the top 500
drug_list = random.sample(list(set(drug_list)),600)#take a random unique sample of 300
drug = pd.DataFrame(drug_list, columns=['drug_name']) #make the list into a dataframe

In [6]:
drug['drug_name'] = drug['drug_name'].replace('-', '.', regex=True)
drug['drug_name'] = drug['drug_name'].replace(' ', '.', regex=True)

prescriber_info['drug_name'] = prescriber_info['drug_name'].replace('-', '.', regex=True)
prescriber_info['drug_name'] = prescriber_info['drug_name'].replace(' ', '.', regex=True)

In [7]:
prescriber = prescriber_info.groupby(['npi','nppes_provider_last_org_name','nppes_provider_first_name','drug_name'])['total_claim_count'].sum()

In [8]:
pres = prescriber.to_frame()

In [40]:
trial_pres = pres.reset_index()

In [42]:
trial_pres.loc[trial_pres['drug_name'] == 'ALVESCO']

,npi,nppes_provider_last_org_name,nppes_provider_first_name,drug_name,total_claim_count
11161,1003031691,HALL,WILLIAM,ALVESCO,14
21499,1003070350,CHAWLA,HARSH,ALVESCO,19
35868,1003115502,SKUPIN,MELISSA,ALVESCO,13

In [11]:
tester=trial_pres.pivot(index='npi',columns='drug_name', values='total_claim_count')

In [39]:
trial_pres

,npi,nppes_provider_last_org_name,nppes_provider_first_name,drug_name,total_claim_count
0,1003000126,ENKESHAFI,ARDALAN,ALVESCO,13
1,1003000126,ENKESHAFI,ARDALAN,ALVESCO,27
2,1003000126,ENKESHAFI,ARDALAN,ALVESCO,17
3,1003000126,ENKESHAFI,ARDALAN,ALVESCO,12
4,1003000126,ENKESHAFI,ARDALAN,ALVESCO,17
...,...,...,...,...,...
99736,1003814419,FISCH,FRED,ALVESCO,1382
99737,1003814419,FISCH,FRED,ALVESCO,19
99738,1003814419,FISCH,FRED,ALVESCO,22
99739,1003814419,FISCH,FRED,ALVESCO,607
99740,1003814419,FISCH,FRED,ALVESCO,65

In [12]:
tester = tester.fillna(0)

In [13]:
list_to_sort= tester.keys().to_list()

In [24]:
sorted_df=drop_columns(list_to_sort,tester)

In [23]:
def drop_columns(list_to_sort,df):
    keep_list=[]
    drop_list=[]
    for i in range(0, len(list_to_sort)):
        if list_to_sort[i] in drug_list:
            True
        else:
            drop_list.append(list_to_sort[i])
    df = df.drop(drop_list, axis=1)
    return df

In [45]:
sorted_df

drug_name,ACETYLCYSTEINE,ACTEMRA,ACYCLOVIR,ALLOPURINOL,ALPRAZOLAM,ALVESCO,AMARYL,AMBIEN,ANDROGEL,APREPITANT,...,ZAFIRLUKAST,ZEMAIRA,ZENPEP,ZETIA,ZONISAMIDE,ZORTRESS,ZOSTAVAX,ZUBSOLV,ZYPREXA,ZYTIGA
npi,,,,,,,,,,,,,,,,,,,,,
1003000126,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003000142,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003000167,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003000282,0.0,0.0,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003000407,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003814245,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003814351,0.0,0.0,11.0,66.0,65.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003814393,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003814401,0.0,0.0,0.0,0.0,38.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003814419,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
#Just to check that there are values within my database
sorted_df[''].sum()

46.0

In [47]:
format_data = meta[['npi','nppes_provider_gender', 'nppes_provider_state', 'nppes_credentials', 'specialty_description', 'opioid_bene_count','opioid_claim_count']]

In [51]:
sorted_df = format_data.merge(sorted_df, left_on='npi', right_on="npi")

In [52]:
sorted_df

,npi,nppes_provider_gender,nppes_provider_state,nppes_credentials,specialty_description,opioid_bene_count,opioid_claim_count,ACETYLCYSTEINE,ACTEMRA,ACYCLOVIR,...,ZAFIRLUKAST,ZEMAIRA,ZENPEP,ZETIA,ZONISAMIDE,ZORTRESS,ZOSTAVAX,ZUBSOLV,ZYPREXA,ZYTIGA
0,1003000126,M,MD,M.D.,Internal Medicine,24.0,25.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1003000142,M,OH,M.D.,Anesthesiology,200.0,1040.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1003000167,M,NV,DDS,Dentist,11.0,14.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1003000282,F,TN,FNP,Nurse Practitioner,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1003000407,M,PA,D.O.,Family Practice,11.0,32.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4534,1003814245,M,CT,M.D.,Ophthalmology,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4535,1003814351,F,NY,M.D.,Family Practice,23.0,120.0,0.0,0.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4536,1003814393,M,CA,DDS,Dentist,28.0,28.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4537,1003814401,M,MD,M.D.,Psychiatry & Neurology,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4538,1003814419,M,AZ,O.D.,Optometry,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [85]:
sorted_df['Opioid.Prescriber'] = 1
for i in range(0,len(sorted_df)):
    if (sorted_df['opioid_bene_count'][i]<10 or sorted_df['opioid_bene_count'][i] == 0) & (sorted_df['opioid_bene_count'][i]<10 or sorted_df['opioid_claim_count'][i]==0):
        sorted_df['Opioid.Prescriber'][i] == 0
    else:
        sorted_df['Opioid.Prescriber'][i] == 1

In [75]:
sorted_df

,npi,nppes_provider_gender,nppes_provider_state,nppes_credentials,specialty_description,opioid_bene_count,opioid_claim_count,ACETYLCYSTEINE,ACTEMRA,ACYCLOVIR,...,ZEMAIRA,ZENPEP,ZETIA,ZONISAMIDE,ZORTRESS,ZOSTAVAX,ZUBSOLV,ZYPREXA,ZYTIGA,Opioid.Prescriber
0,1003000126,M,MD,M.D.,Internal Medicine,24.0,25.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,1003000142,M,OH,M.D.,Anesthesiology,200.0,1040.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,1003000167,M,NV,DDS,Dentist,11.0,14.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,1003000282,F,TN,FNP,Nurse Practitioner,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,1003000407,M,PA,D.O.,Family Practice,11.0,32.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4534,1003814245,M,CT,M.D.,Ophthalmology,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4535,1003814351,F,NY,M.D.,Family Practice,23.0,120.0,0.0,0.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4536,1003814393,M,CA,DDS,Dentist,28.0,28.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4537,1003814401,M,MD,M.D.,Psychiatry & Neurology,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4538,1003814419,M,AZ,O.D.,Optometry,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [86]:
sorted_df['Opioid.Prescriber'].sum()

4539

In [91]:
sorted_df.loc[(sorted_df["opioid_bene_count"]<10 | sorted_df["opioid_bene_count"].isnull()) & (sorted_df["opioid_bene_count"]<10 | sorted_df["opioid_claim_count"].isnull()),["Opioid.Prescriber"]] = 0

In [93]:
sorted_df

,npi,nppes_provider_gender,nppes_provider_state,nppes_credentials,specialty_description,opioid_bene_count,opioid_claim_count,ACETYLCYSTEINE,ACTEMRA,ACYCLOVIR,...,ZEMAIRA,ZENPEP,ZETIA,ZONISAMIDE,ZORTRESS,ZOSTAVAX,ZUBSOLV,ZYPREXA,ZYTIGA,Opioid.Prescriber
0,1003000126,M,MD,M.D.,Internal Medicine,24.0,25.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,1003000142,M,OH,M.D.,Anesthesiology,200.0,1040.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,1003000167,M,NV,DDS,Dentist,11.0,14.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,1003000282,F,TN,FNP,Nurse Practitioner,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,1003000407,M,PA,D.O.,Family Practice,11.0,32.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4534,1003814245,M,CT,M.D.,Ophthalmology,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4535,1003814351,F,NY,M.D.,Family Practice,23.0,120.0,0.0,0.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4536,1003814393,M,CA,DDS,Dentist,28.0,28.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4537,1003814401,M,MD,M.D.,Psychiatry & Neurology,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4538,1003814419,M,AZ,O.D.,Optometry,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0